// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_MekHIkxheKrDGC1mSSOWXaRFmbY8rM',
    appId: '1:707202721990:web:53b4592f4ac2d7e333cfc7',
    messagingSenderId: '707202721990',
    projectId: 'my-notes-bogdroid',
    authDomain: 'my-notes-bogdroid.firebaseapp.com',
    storageBucket: 'my-notes-bogdroid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVHoRviJJAgjs73VxckG2LcSlNF_xKtqg',
    appId: '1:707202721990:android:1743b112a00cb8c633cfc7',
    messagingSenderId: '707202721990',
    projectId: 'my-notes-bogdroid',
    storageBucket: 'my-notes-bogdroid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7N5WLgCKjS7c1feM5T8KySCyUsHCROD4',
    appId: '1:707202721990:ios:82029a49c4e7cedc33cfc7',
    messagingSenderId: '707202721990',
    projectId: 'my-notes-bogdroid',
    storageBucket: 'my-notes-bogdroid.appspot.com',
    iosClientId: '707202721990-kn95c6u80n36licrmicuk3bhl9t2e4mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7N5WLgCKjS7c1feM5T8KySCyUsHCROD4',
    appId: '1:707202721990:ios:82029a49c4e7cedc33cfc7',
    messagingSenderId: '707202721990',
    projectId: 'my-notes-bogdroid',
    storageBucket: 'my-notes-bogdroid.appspot.com',
    iosClientId: '707202721990-kn95c6u80n36licrmicuk3bhl9t2e4mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
